#!/usr/bin/env bash
# _ai/scripts/generate-agent-docs.sh
#
# Generates agent-specific entry point files from _ai/skills/ sources.
# Run from project root: bash _ai/scripts/generate-agent-docs.sh
#
# Output:
#   CLAUDE.md                         — Claude Code / Claude CLI instructions
#   .github/copilot-instructions.md   — GitHub Copilot instructions

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
AI_DIR="$PROJECT_ROOT/_ai"
SKILLS_DIR="$AI_DIR/skills"

# --- Helpers ---

join_files() {
  local sep=$'\n\n---\n\n'
  local result=""
  for file in "$@"; do
    if [[ -f "$file" ]]; then
      if [[ -n "$result" ]]; then
        result+="$sep"
      fi
      result+="$(cat "$file")"
    else
      echo "WARNING: $file not found, skipping" >&2
    fi
  done
  echo "$result"
}

# --- Generate CLAUDE.md ---

echo "Generating CLAUDE.md..."
cat > "$PROJECT_ROOT/CLAUDE.md" << 'HEADER'
<!-- Auto-generated by _ai/scripts/generate-agent-docs.sh — do not edit manually -->

HEADER

# Include project-rules first (it's the system prompt), then context and architecture
{
  cat "$SKILLS_DIR/project-rules.md"
  echo -e "\n\n---\n"
  cat "$AI_DIR/context.md"
  echo -e "\n\n---\n"
  cat "$SKILLS_DIR/architecture.md"
  echo -e "\n\n---\n"
  cat "$SKILLS_DIR/decisions.md"
  echo -e "\n\n---\n"
  echo "For reader implementation details, see \`_ai/skills/readers.md\`."
  echo "For current project status, see \`_ai/skills/status.md\`."
} >> "$PROJECT_ROOT/CLAUDE.md"

echo "  → CLAUDE.md ($(wc -l < "$PROJECT_ROOT/CLAUDE.md") lines)"

# --- Generate .github/copilot-instructions.md ---

echo "Generating .github/copilot-instructions.md..."
mkdir -p "$PROJECT_ROOT/.github"

cat > "$PROJECT_ROOT/.github/copilot-instructions.md" << 'HEADER'
<!-- Auto-generated by _ai/scripts/generate-agent-docs.sh — do not edit manually -->

HEADER

{
  cat "$SKILLS_DIR/project-rules.md"
  echo -e "\n\n---\n"
  cat "$AI_DIR/context.md"
  echo -e "\n\n---\n"
  cat "$SKILLS_DIR/architecture.md"
  echo -e "\n\n---\n"
  cat "$SKILLS_DIR/decisions.md"
  echo -e "\n\n---\n"
  echo "For reader implementation details, see \`_ai/skills/readers.md\`."
  echo "For current project status, see \`_ai/skills/status.md\`."
} >> "$PROJECT_ROOT/.github/copilot-instructions.md"

echo "  → .github/copilot-instructions.md ($(wc -l < "$PROJECT_ROOT/.github/copilot-instructions.md") lines)"

echo "Done."
